### ISSUE TITLE
URL rewriter with two admin directories

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAF.SampleWebApplication#2]
If you have two admin directories, how should the urlrewriter.config be setup?  

root/admin
root/forum/admin

I've tried several "ideas" and failed miserably lol

**Comment by w8tcha** [comment]
Do you want to exclude the root admin directory from the rewriter or include?

**Comment by Zero2Cool** [comment]
I think exclude might be the most fluid way. What would you recommend?

**Comment by w8tcha** [comment]
Well i think i depends if the root admin interface has its own url rewriter which might conflict with the yaf url rewriter.

if you want to exclude it then add it to the if statement

```xml
  <if url="^((?!\.ashx|\.asmx|\.axd|\.gif|\.png|\.jpg|\.ico|\.pdf|\.css|\.js|install|error|auth\.aspx|default\.aspx|popup\.aspx|advanced\.aspx|digest\.aspx|~/admin/).)*$">
    <rewrite url="^~/forum/(.+)?\?(.+)?$" to="~/forum/forum.aspx?g=$1&amp;$2" processing="stop" />
    <rewrite url="^~/forum/(.+)?$" to="~/forum/forum.aspx?g=$1" processing="stop" />
    <rewrite url="^~/forum/(.+)?\.aspx$" to="~/forum/forum.aspx?g=$1" processing="stop" /> 
  </if>
```

**Comment by Zero2Cool** [comment]
I did try this right away, but still throwing the same error about not able to find /admin/forum.aspx but the /admin and /forum directories are both in root.

root/admin/
root/forum/admin 

http://www.packerpeople.com/admin/

here's what I have in my urlrewriter config


ï»¿<rewriter>
  
  <if url="^((?!forum).)*$">
     <rewrite url="^~/(.+?)?login?\.aspx(\?(.+))?$" to="~/forum/forum.aspx?g=login&amp;$2" processing="stop" />
  </if>
  <rewrite url="^~/forum/forum\.aspx\?g=login(&amp;(.+))?$" to="~/forum/forum.aspx?g=login&amp;$1" processing="stop" />
  
  <rewrite url="^~/(.+?)?yaf_login?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=login&amp;$3" processing="stop" />
  <rewrite url="^~/(.+?)?yaf_info?\.aspx\?i=([0-9]+?)&amp;url\=(.+)$" to="~/$1Forum.aspx?g=info&amp;i=$2&amp;url=$3" processing="stop" />
  <rewrite url="^~/(.+)?yaf_topics([0-9]+)p([0-9]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=topics&amp;f=$2&amp;p=$3&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?yaf_topics([0-9]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=topics&amp;f=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?yaf_forum([0-9]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=forum&amp;c=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?yaf_postst([0-9]+)find([-a-z]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=posts&amp;t=$2&amp;find=$3&amp;$7" processing="stop" /> 
  <rewrite url="^~/(.+)?yaf_postst([0-9]+)p([0-9]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=posts&amp;t=$2&amp;p=$3&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?yaf_postst([0-9]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=posts&amp;t=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?yaf_postsm([0-9]+)find([-a-z]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=posts&amp;m=$2&amp;find=$3&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?yaf_postsm([0-9]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=posts&amp;m=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?yaf_profile([0-9]+)(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=profile&amp;u=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?yaf_rsstopicft([0-9]+)t([0-9]+)(_([-a-z0-9]+))(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=rsstopic&amp;ft=$2&amp;t=$3&amp;$9" processing="stop" />
  <rewrite url="^~/(.+)?yaf_rsstopicft([0-9]+)f([0-9]+)(_([-a-z0-9]+))(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=rsstopic&amp;ft=$2&amp;f=$3&amp;$9" processing="stop" /> 
  <rewrite url="^~/(.+)?yaf_rsstopicft([0-9]+)(_([-a-z0-9]+))(_([-a-z0-9]+))?\.aspx(\?(.+))?$" to="~/$1Forum.aspx?g=rsstopic&amp;ft=$2&amp;$8" processing="stop" />
  <rewrite url="^~/(.+)?yaf_([-0-9a-z_]+?)\.aspx\?(.+)?$" to="~/$1Forum.aspx?g=$2&amp;$3" processing="stop" />
  <rewrite url="^~/(.+)?yaf_([-0-9a-z_]+?)\.aspx$" to="~/$1Forum.aspx?g=$2" processing="stop" />
  
  <rewrite url="^~/(.+?)?error.aspx$" to="~/$1error.aspx" processing="stop" />
  <rewrite url="^~/(.+?)?install/default.aspx?(\?(.+))?$" to="~/$1install/default.aspx?$2" processing="stop" />
  <rewrite url="^~/(.+?)?install/$" to="~/$1install/default.aspx?$2" processing="stop" />
  <rewrite url="^~/(.+?)?login?(\?(.+))?$" to="~/$1forum.aspx?g=login&amp;$3" processing="stop" />
  <rewrite url="^~/(.+?)?info?\?i=([0-9]+?)&amp;url\=(.+)$" to="~/$1forum.aspx?g=info&amp;i=$2&amp;url=$3" processing="stop" />
  <rewrite url="^~/(.+)?topics/([0-9]+)-(([-a-z0-9]+))?(/page([0-9]+))(\?(.+))?$" to="~/$1forum.aspx?g=topics&amp;f=$2&amp;p=$6&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?topics/([0-9]+)-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=topics&amp;f=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?/category/([0-9]+)-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1/forum.aspx?g=forum&amp;c=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?posts/t([0-9]+)findlastpost-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;t=$2&amp;find=lastpost&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?posts/t([0-9]+)findunread-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;t=$2&amp;find=unread&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?posts/t([0-9]+)-(([-a-z0-9]+))?(/page([0-9]+))(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;t=$2&amp;p=$6&amp;$8" processing="stop" />
  <rewrite url="^~/(.+)?posts/t([0-9]+)-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;t=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?posts/t([0-9]+)?(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;t=$2&amp;$5" processing="stop" />
  <rewrite url="^~/(.+)?posts/m([0-9]+)findlastpost-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;m=$2&amp;find=lastpost&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?posts/m([0-9]+)findunread-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;m=$2&amp;find=unread&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?posts/m([0-9]+)-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=posts&amp;m=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?profile/([0-9]+)-(([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=profile&amp;u=$2&amp;$6" processing="stop" />
  <rewrite url="^~/(.+)?admin/([-a-z0-9]+)?/([-a-z0-9]+)?(\?(.+))?$" to="~/$1forum.aspx?g=admin_$2_$3&amp;$5" processing="stop" />
  <rewrite url="^~/(.+)?admin/([-a-z0-9]+)?(\?(.+))?$" to="~/$1forum.aspx?g=admin_$2&amp;$4" processing="stop" />
  <rewrite url="^~/(.+)?rsstopic/ft([0-9]+)t([0-9]+)-(([-a-z0-9]+))(_([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=rsstopic&amp;ft=$2&amp;t=$3&amp;pg=$5&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?rsstopic/ft([0-9]+)f([0-9]+)-(([-a-z0-9]+))(_([-a-z0-9]+))?(\?(.+))?$" to="~/$1forum.aspx?g=rsstopic&amp;ft=$2&amp;f=$3&amp;pg=$5&amp;$7" processing="stop" /> 
  <rewrite url="^~/(.+)?rsstopic/ft([0-9]+)-(([-a-z0-9]+))_([-a-z0-9]+)(\?(.+))?$" to="~/$1forum.aspx?g=rsstopic&amp;ft=$2&amp;pg=$3&amp;$7" processing="stop" />
  <rewrite url="^~/(.+)?rsstopic/ft([0-9]+)-(([-a-z0-9]+))-([-a-z0-9]+)(\?(.+))?$" to="~/$1forum.aspx?g=rsstopic&amp;ft=$2&amp;pg=$3&amp;$7" processing="stop" />
  
<if url="^((?!\.ashx|\.asmx|\.axd|\.gif|\.png|\.jpg|\.ico|\.pdf|\.css|\.js|install|error|auth\.aspx|forum\.aspx|popup\.aspx|advanced\.aspx|digest\.aspx|~/admin/|/auth|/popup).)*$">
    <rewrite url="^~/forum/(.+)?\?(.+)?$" to="~/forum/forum.aspx?g=$1&amp;$2" processing="stop" />
    <rewrite url="^~/forum/(.+)?$" to="~/forum/forum.aspx?g=$1" processing="stop" />
    <rewrite url="^~/forum/(.+)?\.aspx$" to="~/forum/forum.aspx?g=$1" processing="stop" />
  </if>
</rewriter>

**Comment by w8tcha** [comment]
sorry you also need to modify the lines

```xml
<rewrite url="^~/(.+)?admin/([-a-z0-9]+)?/([-a-z0-9]+)?(\?(.+))?$" to="~/$1forum.aspx?g=admin_$2_$3&amp;$5" processing="stop" />
<rewrite url="^~/(.+)?admin/([-a-z0-9]+)?(\?(.+))?$" to="~/$1forum.aspx?g=admin_$2&amp;$4" processing="stop" />
```

to

```xml
<rewrite url="^~/forum/admin/([-a-z0-9]+)?/([-a-z0-9]+)?(\?(.+))?$" to="~/forum/forum.aspx?g=admin_$1_$2&amp;$4" processing="stop" />
<rewrite url="^~/forum/admin/([-a-z0-9]+)?(\?(.+))?$" to="~/forum/forum.aspx?g=admin_$1&amp;$3" processing="stop" />
```

**Comment by Zero2Cool** [comment]
Sweetness!
