### ISSUE TITLE
Integration with a blazor server app

### ISSUE THREAD

**Issue by ltemimi** [YAFNET/YAF.SampleWebApplication#29]
Hi

Is it possible to integrate  YAF with a blazor server app? If yes, where can I find some instructions on ho to do it

Thanks

**Comment by w8tcha** [comment]
No, this is not possible

**Comment by ltemimi** [comment]
Hi

Thanks, I need to deploy to azure as a separate website which I can access from my blazor website. it will have a url xxxx.azurewbsites.net. Will that work with a commercial license?  I need the forum to support the products I sell online.

regards
Laz

**Comment by w8tcha** [comment]
Yes as a separate application you can run the site.
