### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAF.SampleWebApplication#30]
I downloaded the source code and right away got errors when trying to do a build. Is that expected or should this just work out of the box?

Here's the errors I'm getting. The only thing I changed was the database connection string.
![image](https://user-images.githubusercontent.com/5612416/140621223-6a128501-6eff-4125-bd27-501473942192.png)

**Comment by w8tcha** [comment]
The Source code don't include the yaf assemblies.

Download the Source code including the assemblies 

https://github.com/YAFNET/YAF.SampleWebApplication/releases/download/v3.0.0/YAF.SampleWebApplication-v3.0.0.zip

Or manually download the yaf release and copy the files to the bin folder.

**Comment by Zero2Cool** [comment]
D'oh, didn't get the notification you responded. Checking this now.

**Comment by Zero2Cool** [comment]
Closed this issue, but could @w8tcha can you download the source and try running it? I'm getting errors about needing Threading.Tasks.Extensions and once I get that added, there is another one about CompilerServices.Unsafe and I don't want to keep playing whack a mole here if I'm just doing something wrong, or something missing from the solution, lol.

**Comment by w8tcha** [comment]
> Update2: It looks like the GetSafeRawUrl from YAF.Utils.General did not make it to the new YAF.Core.Utilities and that is the issue I'm having regarding the errors with "General".

Looks like some files where not updated in the master branch. Done

**Comment by Zero2Cool** [comment]
Thanks! I'm eating lunch and gave it another shot. Downloaded the source, copied the bin from YAF deploy and still not able to get a clean build. I haven't trouble shot this yet though.

![image](https://user-images.githubusercontent.com/5612416/141346197-ed80090b-e337-404e-9fb2-d7451aab9a73.png)

**Comment by w8tcha** [comment]
It's possible that you have to do a manual nuget restore. Visual Studio does this automatically on build for me

**Comment by Zero2Cool** [comment]
> It's possible that you have to do a manual nuget restore. Visual Studio does this automatically on build for me

I had to remove the MVC stuff from the solution and then got a clean build. I pointed it to a copy of my database and proceeded with the update, however I received this error. is this also because nuget was not restored? 

![image](https://user-images.githubusercontent.com/5612416/141348030-f6b7e1ca-e2b0-4f94-89b6-bf4ec9eb2a48.png)

**Comment by w8tcha** [comment]
> however I received this error. is this also because nuget was not restored?

No, that seems an issue with yaf, and not the sampleapplication

**Comment by w8tcha** [comment]
i commited an updated web.config. can you check if it works with the updated web.config?!
