### ISSUE TITLE
Chat not connecting to Hubs

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAF.SampleWebApplication#34]
It looks like the Chat hubs isn't being initiated. I tried my Sample Application that I modified for my website and it fires off when the Chat loads. Gonna poke around in this one.

![image](https://user-images.githubusercontent.com/5612416/143292795-50af3805-0f31-48f8-a248-4362dbab31cc.png)

![image](https://user-images.githubusercontent.com/5612416/143292744-21169a5b-a2e8-4483-9841-593c213fdc93.png)

**Comment by Zero2Cool** [comment]
Latest commit did not fix this, it only renamed the startup file. 😐

**Comment by w8tcha** [comment]
Sorry I did not mention. But you also need to update the YAFNET main repository to the latest commit

**Comment by Zero2Cool** [comment]
> Sorry I did not mention. But you also need to update the YAFNET main repository to the latest commit

I downloaded the latest commit source code. That should be sufficient right?

**Comment by w8tcha** [comment]
> > Sorry I did not mention. But you also need to update the YAFNET main repository to the latest commit
> 
> 
> 
> I downloaded the latest commit source code. That should be sufficient right? 

Correct
