### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAF.SampleWebApplication#4]
Click Login, enter username and password and click Forum Login and this is the error in the console you get. Nothing further happens.

This is from commit 744e81f9d724e3e8341b1214aa6077730727de47

![image](https://user-images.githubusercontent.com/5612416/58838799-5afdb880-8625-11e9-9f3c-bbea6ea0251d.png)

**Comment by w8tcha** [comment]
Should be fixed now
