### ISSUE TITLE
TypeError: $(...).suggest is not a function     at postmessage?t=28173&f=4:1917

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAF.SampleWebApplication#5]
Any thoughts on what would be the cause of this?

![image](https://user-images.githubusercontent.com/5612416/69541544-ff1a4980-0f4e-11ea-8102-c7db484849c9.png)
![image](https://user-images.githubusercontent.com/5612416/69541613-2c66f780-0f4f-11ea-9f25-f8e7da991082.png)

**Comment by w8tcha** [comment]
I guess it will work, when the $ is replaced by jquery. Should be fixed with 2.30.02!

**Comment by w8tcha** [comment]
Is the issue resolved?
