### ISSUE TITLE
getSearchResultsData is not defined

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAF.SampleWebApplication#6]
I'm not sure if this is a Sample Application issue or something on my end. I'm thinking it's my end, but I'm not sure what it could be.  I tried to do a search and it worked, then tried searching again and got that error. 

![image](https://user-images.githubusercontent.com/5612416/69545274-15c49e80-0f57-11ea-9de4-830a8fec2105.png)

**Comment by w8tcha** [comment]
Is this still reproduceable?

**Comment by Zero2Cool** [comment]
I am not experiencing this any longer. I'm guessing it was a folder permissions issue of some kind.
