### ISSUE TITLE
Get Search Results error

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAF.SampleWebApplication#65]
Trying to upgrade again and seems most things are working except the search. The URL for the test site is below.
http://kevinduganjr-002-site2.etempurl.com/

Click Search and search for "barry sanders" and this error happens.

Requested URL: /api/Search/GetSearchResults

I've tried doing this with just standalone YAF and no error, but the results show "no results found" unless it was post created after the update.

**Comment by w8tcha** [comment]
I commited an update, seach and all other web api controller should work now.

> I've tried doing this with just standalone YAF and no error, but the results show "no results found" unless it was post created after the update.

If the search index was never created or you delete the app_data folder on upgrade then you need to create the seach index first.

**Comment by KevinDuganJr** [comment]
No more error. Woohoo!

How do I create the search index? I've tried forcing an upgrade, but I think the default url rewriter might be redirecting back to home.

**Comment by w8tcha** [comment]
> No more error. Woohoo!
> 
> How do I create the search index? I've tried forcing an upgrade, but I think the default url rewriter might be redirecting back to home.

Via Host Settings > Search > Re-Index Search

**Comment by KevinDuganJr** [comment]
> > No more error. Woohoo!
> > How do I create the search index? I've tried forcing an upgrade, but I think the default url rewriter might be redirecting back to home.
> 
> Via Host Settings > Search > Re-Index Search

Nice. The fix worked. And you of course had a built-in fix for the indexing. I didn't even think about looking. I was trying to build it manually haha.

**Comment by w8tcha** [comment]
Well you could have also waited until 5 am then the task is executed automatically every day 😉

**Comment by KevinDuganJr** [comment]
It's almost 10am now so maybe it did? Or 5am UTC?

**Comment by w8tcha** [comment]
Based on the server local time. if you have info logging enabled in the host settings, then the info about the task is excecuted is logged to the event log

**Comment by KevinDuganJr** [comment]
Nice. I'll have to check that out. How long before the search index is built that it pulls up all posts? I've done searches on posts that I know are old and nothing comes up.

**Comment by w8tcha** [comment]
Yes it should index all messages

**Comment by KevinDuganJr** [comment]
> Yes it should index all messages

Hmm, I wonder why it didn't.

**Comment by w8tcha** [comment]
> > Yes it should index all messages
> 
> 
> 
> Hmm, I wonder why it didn't.

I don't know with any more detail I can not try to reproduce it.

**Comment by KevinDuganJr** [comment]
It's weird for sure. I'm not sure how to provide more detail. I'll see what more information I can find. But really, all I did was search for text I know is in posts. I checked my mom's first name. She died 2008. Zero posts showed up. And the topic and posts still exist.

**Comment by KevinDuganJr** [comment]
Turns out, the App_Data with the search index works much better. I copied that over and now I'm pulling up those old threads.
