### ISSUE TITLE
Tags and Attachments not working

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAF.SampleWebApplication#71]
Tags and Attachments stopped working in Sample Application with the latest YAF standalone commit. 

YAF Standalone aimed at the same database works just fine. So, I have something wrong in my Sample Application, but it works with the previous YAF version I had so I am not sure what is up.  

![image](https://github.com/YAFNET/YAF.SampleWebApplication/assets/5612416/d1923ed5-609d-47cb-b70f-15573c34653e)
![image](https://github.com/YAFNET/YAF.SampleWebApplication/assets/5612416/9b9190ae-bf76-40e1-a7fb-3e7b6d8fe9e4)

**Comment by w8tcha** [comment]
Did you upate the js files and clear the browser cache, or make a force reload?

**Comment by KevinDuganJr** [comment]
> Did you upate the js files and clear the browser cache, or make a force reload?

/Scripts has not been updated
/Forum/Scripts was updated

Yes, browser cache cleared and forced reload. 

My /Forum directory has the files from the Upgrade ZIP.
My /bin directory has the upgrade/bin DLL's.

YAF Standalone works beautifully for Tags and Attachments.

I'm just not sure what I have wrong. JavaScript things always kill me. I can't ever seem to debug those issues with any success.

**Comment by w8tcha** [comment]
> My test site is online. You don't need to log in to see console error. You just need to view topics in a forum.

As suspected the file jquery.ForumExtensions.js is not up to date. You are running the app in debug mode then the unmodified version of  jquery.ForumExtensions.js is used. i guess you only updated the minified version  jquery.ForumExtensions.min.js

**Comment by KevinDuganJr** [comment]
I'll check in a bit. But I'm using the files from the deploy package so it shouldn't be debug. And the sample application files are from the publish directory.

**Comment by w8tcha** [comment]
It doesn't matter if yaf was compiled in debug. Is the sample application compiled on debug mode? Also debug mode can be enabled in the webconfig

**Comment by KevinDuganJr** [comment]
> It doesn't matter if yaf was compiled in debug. Is the sample application compiled on debug mode? Also debug mode can be enabled in the webconfig

I made a copy of jquery.ForumExtensions.min.js and removed 'min' and it worked. I am not sure what happened or why it pointed to the unminified version this time but each time before was fine. 🤷‍♂️ Anyhow, thank you for pointing me in right direction.
