### ISSUE TITLE
Infinite Loop on Login

### ISSUE THREAD

**Issue by KevinDuganJr** [YAFNET/YAF.SampleWebApplication#72]
https://github.com/YAFNET/YAF.SampleWebApplication/assets/5612416/a2660bd9-5908-4405-8b9e-7218457d7f1f

If you click "Login", the page repeatedly displays the notification below.  

You can see it in action over at www.PackersHome.com and click the "Login" button in upper right corner in the navbar.

The login button on the forum works, but I'm not a fan of modals (we developers over use them) and always use the actual login page. 

![image](https://github.com/YAFNET/YAF.SampleWebApplication/assets/5612416/44a47943-773f-4607-af0f-b24348af8df7)

**Comment by KevinDuganJr** [comment]
This is actually a YAF Stand Alone related issue. I just reproduced it using YAF. So, just a rewriter issue is my guess.

**Comment by w8tcha** [comment]
Issue is fixed now in YAF
