### ISSUE TITLE
Items require second click when not in forum

### ISSUE THREAD

**Issue by Zero2Cool** [YAFNET/YAF.SampleWebApplication#8]
I've noticed when I'm outside of the forum, I have to double click navbar menu items before action is taken.  I'm thinking there might be some javascript that is being loaded twice? 

Example.  on www.packershome.com/home I click "fantasy" I have to click it a second time to have it expand.

![image](https://user-images.githubusercontent.com/5612416/70718633-2ba3c480-1cb6-11ea-9389-22843aacd676.png)

**Comment by w8tcha** [comment]
I see in your code 

`<script src="Forum/Scripts/popper.js" type="text/javascript"></script>`

this causing the issue! and its not part of the sample application or the forum

**Comment by Zero2Cool** [comment]
Nice catch. I removed that, but same thing.

**Comment by w8tcha** [comment]
There is also boostrap loaded twice on your site...

`<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>`

**Comment by Zero2Cool** [comment]
I'll double check again, but I'm not sure what could be loading it.

**Comment by Zero2Cool** [comment]
Ugh. That was it. I was focusing on everything EXCEPT the actual pages I brought over from the previous version of my site. Thank you.
